### ISSUE TITLE
При попытки получить информацию о чеке вылезает ошибка.

### ISSUE THREAD

**Issue by medovi40k** [QIWI-API/bill-payments-php-sdk#21]
Запрашиваю информацию о чеке и вылетает ошибка 
```
PHP Fatal error:  Uncaught Qiwi\Api\BillPaymentsException: HTTP/1.1 401 Unauthorized in /vendor/qiwi/bill-payments-php-sdk/src/BillPayments.php:592
Stack trace:
#0 /vendor/qiwi/bill-payments-php-sdk/src/BillPayments.php(487): Qiwi\Api\BillPayments->requestBuilder('640d989f-3a0f-4...')
#1 test.php(10): Qiwi\Api\BillPayments->getBillInfo('***')
#2 {main}
  thrown in /vendor/qiwi/bill-payments-php-sdk/src/BillPayments.php on line 592

```

Код:
```
require 'vendor/autoload.php';
$publicKey = '***';
const SECRET_KEY = '***';
$billPayments = new Qiwi\Api\BillPayments(SECRET_KEY);
$billId = '**';


/** @var \Qiwi\Api\BillPayments $billPayments */
$response = $billPayments->getBillInfo($billId);

print_r($response);
```

**Comment by medovi40k** [comment]
Решено. Не правильно скопирован секретный ключ.
